@echo off
echo Running first script...
python.exe ""C:\Users\Bananberg\Desktop\GPdatabase\GP_database_auto\scripts\migration.py""
echo Running second script...
python.exe ""C:\Users\Bananberg\Desktop\GPdatabase\GP_database_auto\scripts\update_gpfile.py""
